Kitware/pan3d

pan3d/viewer/engine.py
pan3d/viewer/ui.py
setup.cfg

- Move dataset selection box to sidebar
- Automatically select first available array once a dataset is ready
- Remove "reset view" button, automatically invoke reset on state changes
- Add error banner above render area to tell the user when/why an auto view reset fails
- Reorganize axis selection options to reduce redundant information

UI redesign

---

pan3d/__main__.py
pan3d/dataset_builder.py
pan3d/ui/axis_configure.py
pan3d/ui/axis_selection.py
pan3d/ui/custom.css
pan3d/ui/main_drawer.py
pan3d/ui/toolbar.py
setup.cfg

Before going too far on the Axis Selector redesign (#29) in Vue 2, I'd like to migrate to Vue 3 and use that API going forward. My pyvista PR was just merged (https://github.com/pyvista/pyvista/pull/4811), and a release will be going out soon.
This PR switches to the Vue 3 client type, and once the pyvista release is made, the pyvista `plotter_ui` function we use will return a compatible interface. 
** Requires pyvista >= 0.42.0 **

Vue 3 migration

---

pan3d/dataset_builder.py

I was able to test out the `pflotran` dataset from @johnkit, and I can confirm it works with Pan3D. We just need a few lines to support the `.nc` version of the data as well.

Allow other xarray engines for other file types

---

pan3d/dataset_builder.py
pan3d/pangeo_forge.py
pan3d/ui/__init__.py
pan3d/ui/main_drawer.py
pan3d/ui/render_options.py
pan3d/utils.py

New render options include:
- colormap
- transparency
- transparency function
- warp by scalars
- x scale
- y scale
- z scale
(Additionally, the colormap scale key is interactive; it can be resized and moved. This is functionality built into Pyvista.)

Add UI panel to change render options

---

.github/workflows/test_and_release.yml

- Python semantic release has changed their API as of version 8 to no longer offer PyPI publishing. This PR follows their migration guide. https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html
- PyPI publishing is now done as a separate step using `pypa/gh-action-pypi-publish`, as recommended by the PyPI docs: https://docs.pypi.org/trusted-publishers/using-a-publisher/
- I have created a pending Trusted Publisher on my PyPI account, which is waiting for the first push from this repository to create the PyPI project.

Update PyPI publishing

---

.github/workflows/test_and_release.yml

The CI config in #35 failed with the following:
```
The workflow is not valid. .github/workflows/test_and_release.yml (Line: 88, Col: 9): Unexpected value 'environment' .github/workflows/test_and_release.yml (Line: 89, Col: 9): Unexpected value 'permissions'
```
This PR changes the yml file by separating the PyPI publish step as its own job after the semantic release job. This time the job definition was pasted directly from the PyPI documentation.

Fix PyPI publishing step in CI

---

pyproject.toml

After merging #40, the PyPI publish action failed because the file for the "1.0.0" version exists already. The PyPI action is currently not using the git tag, it uses the static string in `pyproject.toml`. This PR changes that line to use dynamic versions from git tags. 
This fix was found here: https://stackoverflow.com/questions/72270892/git-versioning-with-setuptools-in-pyproject-toml

Use dynamic version in pyproject.toml

---

examples/jupyter/Dockerfile
examples/jupyter/requirements.txt

Currently, running the example notebooks on Binder gives the following error:
This may be due to the fact that we should install `vtk-osmesa` in the binder kernel, so this PR makes that addition to `examples/jupyter/requirements.txt`.

Add `vtk-osmesa` to requirements for binder

---

.github/workflows/test_and_release.yml
pyproject.toml
setup.py

Currently, the build action always generates a tar and wheel for version 0.0.0. This results in a failure of the PyPI publish step because v0.0.0 already exists. This PR fixes the build step by adding `setuptools_scm` to `pyproject.toml`. The result should be that PyPI is updated with a version >0.0.0.

Fix build versioning

---

pan3d/dataset_builder.py
pan3d/utils.py
pyproject.toml

This PR fixes the following errors we had been seeing:
1. `Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions`
2. Initial camera reset not working in cloud environments where we set default rendering mode to "client"

Client rendering fixes

---

examples/jupyter/advanced_pyvista_rendering.ipynb
examples/jupyter/import_config_esgf.ipynb
examples/jupyter/import_config_pangeo.ipynb

This PR includes a change that should have been part of #67. Towards the end of that PR, we changed the API to specify which catalogs should be used. I should have updated the examples with that change. This PR includes one commit which modifies the jupyter notebook examples with the new `catalogs` argument . One small additional change is purely aesthetic: adding a markdown cell to `advanced_pyvista_rendering.ipynb` to show the GIF output.

Update example notebooks with catalogs argument

---

docs/api/configuration.md
docs/tutorials/dataset_viewer.md
examples/example_config_esgf.json
examples/example_config_noaa.json
examples/example_config_pangeo.json
pan3d/dataset_builder.py
pan3d/dataset_viewer.py
pan3d/ui/render_options.py
pan3d/utils.py
pyproject.toml
tests/test_builder.py
tests/test_viewer.py

Resolves #18.
This PR adds a flag "render_cartographic" to the `DatasetViewer` state. When enabled, the current data will be rendered on the surface of a sphere with an earth texture. To accomplish this, we now use a `GeoPlotter` from the `geovista` library, which inherits from `pyvista.Plotter`. This PR adds `geovista` to the dependencies for the viewer.
The video below shows basic usage of the cartographic flag:
https://github.com/Kitware/pan3d/assets/44912689/ae8b9dd0-124f-42b2-b4be-6aef0e5638a9
Edit: This PR also includes one semi-unrelated chage; the dataset I tested this feature on was incompatible with the type checking implemented in #70. I removed the check for numeric typing on the values in a slicing array, because we should allow strings for start and stop values of time axes.

Add cartographic rendering mode

---

docs/tutorials/command_line.md
pan3d/serve_viewer.py

Remove shorthand notations of cmdline args

---

pan3d/dataset_viewer.py

It appears that certain cftime objects do not readily support conversion to DateTime objects. This change just returns the string for the cftime object in such a failure.
This also fixes two failing examples:
`example_config_cmip` and `example_config_esgf`

Adding exception handling for cftime to datetime conversion

---

pan3d/dataset_viewer.py
pan3d/ui/bounds_configure.py
pan3d/ui/render_options.py
pan3d/utils.py

Resolves #86.
Closes menu components when the nearby drawer changes state. The Bounds Configuration menu closes when the main drawer changes state, and the Render Options menu closes when the axis drawer changes state.

Fix menu/drawer overlap bug

---

examples/example_config_esgf.json

This change sets the time dimension of the data to the T coordinate
instead of the Z coordinate while the example launches.

Fixing ESGF example : Set time dimension to t instead of z

---

pan3d/explorers/contour.py
pan3d/explorers/globe.py
pan3d/explorers/slicer.py
pan3d/utils/presets.py

Adding look up table changes to fix https://github.com/Kitware/pan3d/issues/143

fix(lookup tables): Adding lookup table changes to explorers

---

pan3d/explorers/globe.py
pan3d/explorers/slicer.py
pan3d/xarray/accessor.py

Making the explorers more consistent in naming and behavior

fix (explorer consistency): Making explorer name and constructor arguments consistent

---

pan3d/explorers/slicer.py
pan3d/ui/slicer.py

Fixing issue when Slice slider won't show when the Summary toolbar is collapsed

fix(slice explorer): Slice slider won't show with summary toolbar

---

examples/jupyter/janelia_cosem_dataset.ipynb

@aashish24 @johnkit @jourdain This is an example of a Janelia dataset being used with Pan3D.
I also propose we make a Volume Explorer -- which is able to do volume rendering and Axis aligned slicing 
To produce visualization like these

fix(janelia example): Adding Janelia COSEM example notebook

---

src/pan3d/widgets/color_by.py

This is to fix the issues @johnkit mentioned about not being able to color the COSEM datasets. #211

fix: force scalar mapping to use LUT
